# This workflow runs static analysis on RepoBee

name: static-analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements.test.txt
        pip install -e .[TEST]
    - name: Lint with flake8
      run: flake8 . --statistics
    - name: Lint with pylint
      run: pylint repobee_junit4
    - name: Lint with Bandit
      run: bandit -r repobee_junit4 -ll
    - name: Check with Black
      run: black --check .
